# Module 3 — LLM Generation & RAG / No-RAG

**Project:** RAG Evaluation: Effect of Chunking Strategy and Retrieval Parameters on Answer Quality

## What this notebook does
1. Loads Module 2's `retrieval_results` CSV.
2. Loads a Qwen instruction model.
3. Generates one answer with retrieved context (RAG).
4. Generates a baseline answer without retrieved context (No-RAG).
5. Saves a CSV that Module 4 can score.

**Input expected from Module 2:** `config_id`, `query`, `chunk_size`, `overlap`, `top_k`, `rank`, `paper_id`, `section`, `text`, and `similarity_score`.

Run this notebook in Google Colab with **Runtime → Change runtime type → T4 GPU** if available.

## Cell 1 — Install required packages

In [1]:

%pip install -q transformers accelerate pandas==2.2.3

## Cell 2 — Check GPU and import libraries

In [2]:
import os
import gc
import json
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("WARNING: No GPU detected. The model may run slowly on CPU.")

PyTorch: 2.11.0+cu130
CUDA available: True
GPU: Tesla T4

## Cell 3 — Upload Module 2's CSV output

In Module 2 notebook, export the DataFrame with:

```python
retrieval_results.to_csv("module_2_retrieval_results.csv", index=False)
```

In [3]:
import zipfile
import os
from google.colab import files

uploaded = files.upload()


# Search for CSV files among uploaded and extracted files
csv_files = [name for name in uploaded.keys() if name.lower().endswith(".csv")]
if not csv_files:
    raise ValueError("No CSV file found. Please upload the Module 2 retrieval-results CSV or a ZIP containing it.")

INPUT_CSV = csv_files[0]
retrieval_results = pd.read_csv(INPUT_CSV)
print("Loaded:", INPUT_CSV)
print("Shape:", retrieval_results.shape)
print("Columns:", retrieval_results.columns.tolist())
display(retrieval_results.head())

Saving module_2_retrieval_results.csv to module_2_retrieval_results.csv
Loaded: module_2_retrieval_results.csv
Shape: (11400, 13)
Columns: ['config_id', 'query_id', 'query', 'chunk_size', 'overlap', 'top_k', 'rank', 'window_id', 'parent_chunk_id', 'paper_id', 'section', 'text', 'similarity_score']

,config_id,query_id,query,chunk_size,overlap,top_k,rank,window_id,parent_chunk_id,paper_id,section,text,similarity_score
0,CFG_001,Q001,What problem does Retrieval-Augmented Generati...,250,0,1,1,C000594_W001,C000594,P10,1 Introduction,retrieval - augmented generation ( rag ) syste...,0.879269
1,CFG_001,Q002,What are the two main components combined in t...,250,0,1,1,C000114_W001,C000114,P03,I Introduction,how these components intricately collaborate t...,0.751279
2,CFG_001,Q003,What task does Dense Passage Retrieval (DPR) t...,250,0,1,1,C000077_W001,C000077,P02,5 Experiments: Passage Retrieval,"in this section, we evaluate the retrieval per...",0.816723
3,CFG_001,Q004,What is the main purpose of RAGAS?,250,0,1,1,C000166_W001,C000166,P03,VI-A Downstream Task,the core task of rag remains question answerin...,0.675176
4,CFG_001,Q005,What issue is investigated in 'Lost in the Mid...,250,0,1,1,C000153_W001,C000153,P03,IV-A Context Curation,redundant information can interfere with the f...,0.803355

## Cell 4 — Validate and prepare Module 2 data

This handles the long-format output from Module 2: each row is one retrieved chunk. Rows are grouped by question and experiment configuration to create the context for Qwen.

In [4]:
required_columns = {
    "query", "chunk_size", "overlap", "top_k", "rank",
    "paper_id", "section", "text", "similarity_score"
}
missing = required_columns - set(retrieval_results.columns)
if missing:
    raise ValueError(
        f"Missing expected Module 2 columns: {sorted(missing)}. "
        "Check that you uploaded retrieval_results, not the original documents CSV."
    )

# Some versions may not contain config_id; create a stable configuration label if absent.
if "config_id" not in retrieval_results.columns:
    retrieval_results["config_id"] = (
        "CH" + retrieval_results["chunk_size"].astype(str)
        + "_OV" + retrieval_results["overlap"].astype(str)
        + "_K" + retrieval_results["top_k"].astype(str)
    )

retrieval_results["rank"] = pd.to_numeric(retrieval_results["rank"], errors="coerce")
retrieval_results["top_k"] = pd.to_numeric(retrieval_results["top_k"], errors="coerce")
retrieval_results["chunk_size"] = pd.to_numeric(retrieval_results["chunk_size"], errors="coerce")
retrieval_results["overlap"] = pd.to_numeric(retrieval_results["overlap"], errors="coerce")
retrieval_results["similarity_score"] = pd.to_numeric(
    retrieval_results["similarity_score"], errors="coerce"
)

retrieval_results["text"] = retrieval_results["text"].fillna("").astype(str)
retrieval_results["query"] = retrieval_results["query"].fillna("").astype(str)

retrieval_results = retrieval_results[
    retrieval_results["query"].str.strip().ne("")
    & retrieval_results["text"].str.strip().ne("")
].copy()

print("Valid retrieval rows:", len(retrieval_results))
print("Unique questions:", retrieval_results["query"].nunique())
print("Configurations:", retrieval_results["config_id"].nunique())
print("Chunk sizes:", sorted(retrieval_results["chunk_size"].dropna().unique().tolist()))
print("Overlaps:", sorted(retrieval_results["overlap"].dropna().unique().tolist()))
print("Top-K values:", sorted(retrieval_results["top_k"].dropna().unique().tolist()))

Valid retrieval rows: 11400
Unique questions: 30
Configurations: 80
Chunk sizes: [250, 500, 750, 1000, 1500]
Overlaps: [0, 50, 100, 200]
Top-K values: [1, 3, 5, 10]

## Cell 5 — Load Qwen

In [5]:
MODEL_NAME = "Qwen/Qwen2.5-3B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model_kwargs = {"device_map": "auto"}
if torch.cuda.is_available():
    model_kwargs["torch_dtype"] = torch.float16

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    **model_kwargs
)
model.eval()

print("Loaded model:", MODEL_NAME)
print("Input device:", model.get_input_embeddings().weight.device)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Loaded model: Qwen/Qwen2.5-3B-Instruct
Input device: cuda:0

## Cell 6 — Define answer-generation functions

The RAG and No-RAG calls use the same model and generation settings. The difference is whether the prompt includes retrieved context.

The RAG prompt instructs the model to rely on the supplied excerpts and to say when the excerpts do not contain enough information. This instruction reduces, but cannot eliminate, hallucinations.

In [6]:
MAX_NEW_TOKENS = 220
TEMPERATURE = 0.0  # deterministic / greedy-style generation
MAX_INPUT_TOKENS = 6000  # keep context bounded for this model/runtime

def _generate_from_messages(messages, max_new_tokens=MAX_NEW_TOKENS):
    prompt_text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    inputs = tokenizer(
        prompt_text,
        return_tensors="pt",
        truncation=True,
        max_length=MAX_INPUT_TOKENS
    )
    input_device = model.get_input_embeddings().weight.device
    inputs = {k: v.to(input_device) for k, v in inputs.items()}

    with torch.inference_mode():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    new_tokens = output_ids[0][inputs["input_ids"].shape[1]:]
    answer = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()
    return answer

def generate_no_rag_answer(query):
    messages = [
        {
            "role": "system",
            "content": (
                "You are a careful research assistant. Answer the question clearly. "
                "Do not invent citations or claim to have read documents you were not given. "
                "If you are unsure, say so."
            )
        },
        {"role": "user", "content": query}
    ]
    return _generate_from_messages(messages)

def generate_rag_answer(query, retrieved_context):
    messages = [
        {
            "role": "system",
            "content": (
                "You are a careful research-paper question-answering assistant. "
                "Answer using the supplied context. Do not add unsupported claims. "
                "If the context does not contain enough evidence, explicitly say that "
                "the provided excerpts are insufficient. Keep the answer concise."
            )
        },
        {
            "role": "user",
            "content": (
                f"Question:\n{query}\n\n"
                f"Retrieved research-paper excerpts:\n{retrieved_context}\n\n"
                "Answer the question using the excerpts above. If the answer is not supported "
                "by the excerpts, state that clearly."
            )
        }
    ]
    return _generate_from_messages(messages)

print("Generation functions are ready.")

Generation functions are ready.

## Cell 7 — Build context from ranked chunks

In [7]:
def build_context(group):
    group = group.sort_values("rank", ascending=True)
    parts = []
    for _, row in group.iterrows():
        paper_id = str(row.get("paper_id", "unknown"))
        section = str(row.get("section", "unknown"))
        rank = row.get("rank", "")
        text = str(row.get("text", "")).strip()
        if text:
            parts.append(
                f"[Retrieved chunk rank={rank}; paper_id={paper_id}; section={section}]\n{text}"
            )
    return "\n\n".join(parts)

# Module 2 has one row per retrieved chunk. This creates one group per question/configuration.
group_columns = ["config_id", "query", "chunk_size", "overlap", "top_k"]
experiment_groups = list(
    retrieval_results.groupby(group_columns, dropna=False, sort=False)
)

print("Question/configuration groups to process:", len(experiment_groups))
print("Example group keys:", experiment_groups[0][0] if experiment_groups else "No groups found")

Question/configuration groups to process: 2400
Example group keys: ('CFG_001', 'What problem does Retrieval-Augmented Generation (RAG) aim to address in knowledge-intensive NLP tasks?', np.int64(250), np.int64(0), np.int64(1))

## Cell 8 — Run a small pilot first

In [8]:
PILOT_GROUPS = min(3, len(experiment_groups))
no_rag_cache = {}
pilot_rows = []

for group_index, (keys, group) in enumerate(experiment_groups[:PILOT_GROUPS], start=1):
    config_id, query, chunk_size, overlap, top_k = keys
    context = build_context(group)

    if query not in no_rag_cache:
        no_rag_cache[query] = generate_no_rag_answer(query)

    rag_answer = generate_rag_answer(query, context)

    pilot_rows.append({
        "config_id": config_id,
        "query": query,
        "chunk_size": chunk_size,
        "overlap": overlap,
        "top_k": top_k,
        "rag_answer": rag_answer,
        "no_rag_answer": no_rag_cache[query],
        "retrieved_context": context
    })
    print(f"Completed pilot {group_index}/{PILOT_GROUPS}")

pilot_df = pd.DataFrame(pilot_rows)
display(pilot_df[["query", "chunk_size", "overlap", "top_k", "rag_answer", "no_rag_answer"]])

Completed pilot 1/3
Completed pilot 2/3
Completed pilot 3/3

,query,chunk_size,overlap,top_k,rag_answer,no_rag_answer
0,What problem does Retrieval-Augmented Generati...,250,0,1,Retrieval-Augmented Generation (RAG) aims to a...,Retrieval-Augmented Generation (RAG) aims to a...
1,What are the two main components combined in t...,250,0,1,The two main components combined in the RAG (R...,"The RAG (Red, Amber, Green) approach is common..."
2,What task does Dense Passage Retrieval (DPR) t...,250,0,1,Dense Passage Retrieval (DPR) targets the task...,Dense Passage Retrieval (DPR) targets the task...

## Cell 9 — Run the full generation experiment

In [9]:
all_result_rows = []
no_rag_cache = {}

for group_index, (keys, group) in enumerate(experiment_groups, start=1):
    config_id, query, chunk_size, overlap, top_k = keys
    group = group.sort_values("rank", ascending=True)
    context = build_context(group)

    try:
        if query not in no_rag_cache:
            no_rag_cache[query] = generate_no_rag_answer(query)
        no_rag_answer = no_rag_cache[query]
        rag_answer = generate_rag_answer(query, context)
        status = "success"
        error_message = ""
    except Exception as e:
        rag_answer = ""
        no_rag_answer = no_rag_cache.get(query, "")
        status = "error"
        error_message = repr(e)
        print(f"Error on group {group_index} ({config_id}): {error_message}")

    paper_ids = [
        str(x) for x in group["paper_id"].dropna().drop_duplicates().tolist()
    ]
    chunk_ids = (
        group["parent_chunk_id"].dropna().astype(str).tolist()
        if "parent_chunk_id" in group.columns
        else []
    )
    window_ids = (
        group["window_id"].dropna().astype(str).tolist()
        if "window_id" in group.columns
        else []
    )
    similarity_scores = group["similarity_score"].dropna().tolist()

    all_result_rows.append({
        "config_id": config_id,
        "query": query,
        "chunk_size": chunk_size,
        "overlap": overlap,
        "top_k": top_k,
        "num_retrieved_chunks": len(group),
        "retrieved_paper_ids": json.dumps(paper_ids, ensure_ascii=False),
        "retrieved_parent_chunk_ids": json.dumps(chunk_ids, ensure_ascii=False),
        "retrieved_window_ids": json.dumps(window_ids, ensure_ascii=False),
        "similarity_scores": json.dumps(similarity_scores),
        "retrieved_context": context,
        "rag_answer": rag_answer,
        "no_rag_answer": no_rag_answer,
        "model_name": MODEL_NAME,
        "max_new_tokens": MAX_NEW_TOKENS,
        "generation_mode": "greedy",
        "generation_status": status,
        "error_message": error_message
    })

    if group_index % 5 == 0 or group_index == len(experiment_groups):
        print(f"Processed {group_index}/{len(experiment_groups)} groups")

generation_results = pd.DataFrame(all_result_rows)
print("Generation result shape:", generation_results.shape)
display(generation_results.head())

Processed 5/2400 groups
Processed 10/2400 groups
Processed 15/2400 groups
Processed 20/2400 groups
Processed 25/2400 groups
Processed 30/2400 groups
Processed 35/2400 groups
Processed 40/2400 groups
Processed 45/2400 groups
Processed 50/2400 groups
Processed 55/2400 groups
Processed 60/2400 groups
Processed 65/2400 groups
Processed 70/2400 groups
Processed 75/2400 groups
Processed 80/2400 groups
Processed 85/2400 groups
Processed 90/2400 groups
Processed 95/2400 groups
Processed 100/2400 groups
Processed 105/2400 groups
Processed 110/2400 groups
Processed 115/2400 groups
Processed 120/2400 groups
Processed 125/2400 groups
Processed 130/2400 groups
Processed 135/2400 groups
Processed 140/2400 groups
Processed 145/2400 groups
Processed 150/2400 groups
Processed 155/2400 groups
Processed 160/2400 groups
Processed 165/2400 groups
Processed 170/2400 groups
Processed 175/2400 groups
Processed 180/2400 groups
Processed 185/2400 groups
Processed 190/2400 groups
Processed 195/2400 groups
Processed 200/2400 groups
Processed 205/2400 groups
Processed 210/2400 groups
Processed 215/2400 groups
Processed 220/2400 groups
Processed 225/2400 groups
Processed 230/2400 groups
Processed 235/2400 groups
Processed 240/2400 groups
Processed 245/2400 groups
Processed 250/2400 groups
Processed 255/2400 groups
Processed 260/2400 groups
Processed 265/2400 groups
Processed 270/2400 groups
Processed 275/2400 groups
Processed 280/2400 groups
Processed 285/2400 groups
Processed 290/2400 groups
Processed 295/2400 groups
Processed 300/2400 groups
Processed 305/2400 groups
Processed 310/2400 groups
Processed 315/2400 groups
Processed 320/2400 groups
Processed 325/2400 groups
Processed 330/2400 groups
Processed 335/2400 groups
Processed 340/2400 groups
Processed 345/2400 groups
Processed 350/2400 groups
Processed 355/2400 groups
Processed 360/2400 groups
Processed 365/2400 groups
Processed 370/2400 groups
Processed 375/2400 groups
Processed 380/2400 groups
Processed 385/2400 groups
Processed 390/2400 groups
Processed 395/2400 groups
Processed 400/2400 groups
Processed 405/2400 groups
Processed 410/2400 groups
Processed 415/2400 groups
Processed 420/2400 groups
Processed 425/2400 groups
Processed 430/2400 groups
Processed 435/2400 groups
Processed 440/2400 groups
Processed 445/2400 groups
Processed 450/2400 groups
Processed 455/2400 groups
Processed 460/2400 groups
Processed 465/2400 groups
Processed 470/2400 groups
Processed 475/2400 groups
Processed 480/2400 groups
Processed 485/2400 groups
Processed 490/2400 groups
Processed 495/2400 groups
Processed 500/2400 groups
Processed 505/2400 groups
Processed 510/2400 groups
Processed 515/2400 groups
Processed 520/2400 groups
Processed 525/2400 groups
Processed 530/2400 groups
Processed 535/2400 groups
Processed 540/2400 groups
Processed 545/2400 groups
Processed 550/2400 groups
Processed 555/2400 groups
Processed 560/2400 groups
Processed 565/2400 groups
Processed 570/2400 groups
Processed 575/2400 groups
Processed 580/2400 groups
Processed 585/2400 groups
Processed 590/2400 groups
Processed 595/2400 groups
Processed 600/2400 groups
Processed 605/2400 groups
Processed 610/2400 groups
Processed 615/2400 groups
Processed 620/2400 groups
Processed 625/2400 groups
Processed 630/2400 groups
Processed 635/2400 groups
Processed 640/2400 groups
Processed 645/2400 groups
Processed 650/2400 groups
Processed 655/2400 groups
Processed 660/2400 groups
Processed 665/2400 groups
Processed 670/2400 groups
Processed 675/2400 groups
Processed 680/2400 groups
Processed 685/2400 groups
Processed 690/2400 groups
Processed 695/2400 groups
Processed 700/2400 groups
Processed 705/2400 groups
Processed 710/2400 groups
Processed 715/2400 groups
Processed 720/2400 groups
Processed 725/2400 groups
Processed 730/2400 groups
Processed 735/2400 groups
Processed 740/2400 groups
Processed 745/2400 groups
Processed 750/2400 groups
Processed 755/2400 groups
Processed 760/2400 groups
Processed 765/2400 groups
Processed 770/2400 groups
Processed 775/2400 groups
Processed 780/2400 groups
Processed 785/2400 groups
Processed 790/2400 groups
Processed 795/2400 groups
Processed 800/2400 groups
Processed 805/2400 groups
Processed 810/2400 groups
Processed 815/2400 groups
Processed 820/2400 groups
Processed 825/2400 groups
Processed 830/2400 groups
Processed 835/2400 groups
Processed 840/2400 groups
Processed 845/2400 groups
Processed 850/2400 groups
Processed 855/2400 groups
Processed 860/2400 groups
Processed 865/2400 groups
Processed 870/2400 groups
Processed 875/2400 groups
Processed 880/2400 groups
Processed 885/2400 groups
Processed 890/2400 groups
Processed 895/2400 groups
Processed 900/2400 groups
Processed 905/2400 groups
Processed 910/2400 groups
Processed 915/2400 groups
Processed 920/2400 groups
Processed 925/2400 groups
Processed 930/2400 groups
Processed 935/2400 groups
Processed 940/2400 groups
Processed 945/2400 groups
Processed 950/2400 groups
Processed 955/2400 groups
Processed 960/2400 groups
Processed 965/2400 groups
Processed 970/2400 groups
Processed 975/2400 groups
Processed 980/2400 groups
Processed 985/2400 groups
Processed 990/2400 groups
Processed 995/2400 groups
Processed 1000/2400 groups
Processed 1005/2400 groups
Processed 1010/2400 groups
Processed 1015/2400 groups
Processed 1020/2400 groups
Processed 1025/2400 groups
Processed 1030/2400 groups
Processed 1035/2400 groups
Processed 1040/2400 groups
Processed 1045/2400 groups
Processed 1050/2400 groups
Processed 1055/2400 groups
Processed 1060/2400 groups
Processed 1065/2400 groups
Processed 1070/2400 groups
Processed 1075/2400 groups
Processed 1080/2400 groups
Processed 1085/2400 groups
Processed 1090/2400 groups
Processed 1095/2400 groups
Processed 1100/2400 groups
Processed 1105/2400 groups
Processed 1110/2400 groups
Processed 1115/2400 groups
Processed 1120/2400 groups
Processed 1125/2400 groups
Processed 1130/2400 groups
Processed 1135/2400 groups
Processed 1140/2400 groups
Processed 1145/2400 groups
Processed 1150/2400 groups
Processed 1155/2400 groups
Processed 1160/2400 groups
Processed 1165/2400 groups
Processed 1170/2400 groups
Processed 1175/2400 groups
Processed 1180/2400 groups
Processed 1185/2400 groups
Processed 1190/2400 groups
Processed 1195/2400 groups
Processed 1200/2400 groups
Processed 1205/2400 groups
Processed 1210/2400 groups
Processed 1215/2400 groups
Processed 1220/2400 groups
Processed 1225/2400 groups
Processed 1230/2400 groups
Processed 1235/2400 groups
Processed 1240/2400 groups
Processed 1245/2400 groups
Processed 1250/2400 groups
Processed 1255/2400 groups
Processed 1260/2400 groups
Processed 1265/2400 groups
Processed 1270/2400 groups
Processed 1275/2400 groups
Processed 1280/2400 groups
Processed 1285/2400 groups
Processed 1290/2400 groups
Processed 1295/2400 groups
Processed 1300/2400 groups
Processed 1305/2400 groups
Processed 1310/2400 groups
Processed 1315/2400 groups
Processed 1320/2400 groups
Processed 1325/2400 groups
Processed 1330/2400 groups
Processed 1335/2400 groups
Processed 1340/2400 groups
Processed 1345/2400 groups
Processed 1350/2400 groups
Processed 1355/2400 groups
Processed 1360/2400 groups
Processed 1365/2400 groups
Processed 1370/2400 groups
Processed 1375/2400 groups
Processed 1380/2400 groups
Processed 1385/2400 groups
Processed 1390/2400 groups
Processed 1395/2400 groups
Processed 1400/2400 groups
Processed 1405/2400 groups
Processed 1410/2400 groups
Processed 1415/2400 groups
Processed 1420/2400 groups
Processed 1425/2400 groups
Processed 1430/2400 groups
Processed 1435/2400 groups
Processed 1440/2400 groups
Processed 1445/2400 groups
Processed 1450/2400 groups
Processed 1455/2400 groups
Processed 1460/2400 groups
Processed 1465/2400 groups
Processed 1470/2400 groups
Processed 1475/2400 groups
Processed 1480/2400 groups
Processed 1485/2400 groups
Processed 1490/2400 groups
Processed 1495/2400 groups
Processed 1500/2400 groups
Processed 1505/2400 groups
Processed 1510/2400 groups
Processed 1515/2400 groups
Processed 1520/2400 groups
Processed 1525/2400 groups
Processed 1530/2400 groups
Processed 1535/2400 groups
Processed 1540/2400 groups
Processed 1545/2400 groups
Processed 1550/2400 groups
Processed 1555/2400 groups
Processed 1560/2400 groups
Processed 1565/2400 groups
Processed 1570/2400 groups
Processed 1575/2400 groups
Processed 1580/2400 groups
Processed 1585/2400 groups
Processed 1590/2400 groups
Processed 1595/2400 groups
Processed 1600/2400 groups
Processed 1605/2400 groups
Processed 1610/2400 groups
Processed 1615/2400 groups
Processed 1620/2400 groups
Processed 1625/2400 groups
Processed 1630/2400 groups
Processed 1635/2400 groups
Processed 1640/2400 groups
Processed 1645/2400 groups
Processed 1650/2400 groups
Processed 1655/2400 groups
Processed 1660/2400 groups
Processed 1665/2400 groups
Processed 1670/2400 groups
Processed 1675/2400 groups
Processed 1680/2400 groups
Processed 1685/2400 groups
Processed 1690/2400 groups
Processed 1695/2400 groups
Processed 1700/2400 groups
Processed 1705/2400 groups
Processed 1710/2400 groups
Processed 1715/2400 groups
Processed 1720/2400 groups
Processed 1725/2400 groups
Processed 1730/2400 groups
Processed 1735/2400 groups
Processed 1740/2400 groups
Processed 1745/2400 groups
Processed 1750/2400 groups
Processed 1755/2400 groups
Processed 1760/2400 groups
Processed 1765/2400 groups
Processed 1770/2400 groups
Processed 1775/2400 groups
Processed 1780/2400 groups
Processed 1785/2400 groups
Processed 1790/2400 groups
Processed 1795/2400 groups
Processed 1800/2400 groups
Processed 1805/2400 groups
Processed 1810/2400 groups
Processed 1815/2400 groups
Processed 1820/2400 groups
Processed 1825/2400 groups
Processed 1830/2400 groups
Processed 1835/2400 groups
Processed 1840/2400 groups
Processed 1845/2400 groups
Processed 1850/2400 groups
Processed 1855/2400 groups
Processed 1860/2400 groups
Processed 1865/2400 groups
Processed 1870/2400 groups
Processed 1875/2400 groups
Processed 1880/2400 groups
Processed 1885/2400 groups
Processed 1890/2400 groups
Processed 1895/2400 groups
Processed 1900/2400 groups
Processed 1905/2400 groups
Processed 1910/2400 groups
Processed 1915/2400 groups
Processed 1920/2400 groups
Processed 1925/2400 groups
Processed 1930/2400 groups
Processed 1935/2400 groups
Processed 1940/2400 groups
Processed 1945/2400 groups
Processed 1950/2400 groups
Processed 1955/2400 groups
Processed 1960/2400 groups
Processed 1965/2400 groups
Processed 1970/2400 groups
Processed 1975/2400 groups
Processed 1980/2400 groups
Processed 1985/2400 groups
Processed 1990/2400 groups
Processed 1995/2400 groups
Processed 2000/2400 groups
Processed 2005/2400 groups
Processed 2010/2400 groups
Processed 2015/2400 groups
Processed 2020/2400 groups
Processed 2025/2400 groups
Processed 2030/2400 groups
Processed 2035/2400 groups
Processed 2040/2400 groups
Processed 2045/2400 groups
Processed 2050/2400 groups
Processed 2055/2400 groups
Processed 2060/2400 groups
Processed 2065/2400 groups
Processed 2070/2400 groups
Processed 2075/2400 groups
Processed 2080/2400 groups
Processed 2085/2400 groups
Processed 2090/2400 groups
Processed 2095/2400 groups
Processed 2100/2400 groups
Processed 2105/2400 groups
Processed 2110/2400 groups
Processed 2115/2400 groups
Processed 2120/2400 groups
Processed 2125/2400 groups
Processed 2130/2400 groups
Processed 2135/2400 groups
Processed 2140/2400 groups
Processed 2145/2400 groups
Processed 2150/2400 groups
Processed 2155/2400 groups
Processed 2160/2400 groups
Processed 2165/2400 groups
Processed 2170/2400 groups
Processed 2175/2400 groups
Processed 2180/2400 groups
Processed 2185/2400 groups
Processed 2190/2400 groups
Processed 2195/2400 groups
Processed 2200/2400 groups
Processed 2205/2400 groups
Processed 2210/2400 groups
Processed 2215/2400 groups
Processed 2220/2400 groups
Processed 2225/2400 groups
Processed 2230/2400 groups
Processed 2235/2400 groups
Processed 2240/2400 groups
Processed 2245/2400 groups
Processed 2250/2400 groups
Processed 2255/2400 groups
Processed 2260/2400 groups
Processed 2265/2400 groups
Processed 2270/2400 groups
Processed 2275/2400 groups
Processed 2280/2400 groups
Processed 2285/2400 groups
Processed 2290/2400 groups
Processed 2295/2400 groups
Processed 2300/2400 groups
Processed 2305/2400 groups
Processed 2310/2400 groups
Processed 2315/2400 groups
Processed 2320/2400 groups
Processed 2325/2400 groups
Processed 2330/2400 groups
Processed 2335/2400 groups
Processed 2340/2400 groups
Processed 2345/2400 groups
Processed 2350/2400 groups
Processed 2355/2400 groups
Processed 2360/2400 groups
Processed 2365/2400 groups
Processed 2370/2400 groups
Processed 2375/2400 groups
Processed 2380/2400 groups
Processed 2385/2400 groups
Processed 2390/2400 groups
Processed 2395/2400 groups
Processed 2400/2400 groups
Generation result shape: (2400, 18)

,config_id,query,chunk_size,overlap,top_k,num_retrieved_chunks,retrieved_paper_ids,retrieved_parent_chunk_ids,retrieved_window_ids,similarity_scores,retrieved_context,rag_answer,no_rag_answer,model_name,max_new_tokens,generation_mode,generation_status,error_message
0,CFG_001,What problem does Retrieval-Augmented Generati...,250,0,1,1,"[""P10""]","[""C000594""]","[""C000594_W001""]",[0.879269003868103],[Retrieved chunk rank=1; paper_id=P10; section...,Retrieval-Augmented Generation (RAG) aims to a...,Retrieval-Augmented Generation (RAG) aims to a...,Qwen/Qwen2.5-3B-Instruct,220,greedy,success,
1,CFG_001,What are the two main components combined in t...,250,0,1,1,"[""P03""]","[""C000114""]","[""C000114_W001""]",[0.7512792348861694],[Retrieved chunk rank=1; paper_id=P03; section...,The two main components combined in the RAG (R...,"The RAG (Red, Amber, Green) approach is common...",Qwen/Qwen2.5-3B-Instruct,220,greedy,success,
2,CFG_001,What task does Dense Passage Retrieval (DPR) t...,250,0,1,1,"[""P02""]","[""C000077""]","[""C000077_W001""]",[0.8167228698730469],[Retrieved chunk rank=1; paper_id=P02; section...,Dense Passage Retrieval (DPR) targets the task...,Dense Passage Retrieval (DPR) targets the task...,Qwen/Qwen2.5-3B-Instruct,220,greedy,success,
3,CFG_001,What is the main purpose of RAGAS?,250,0,1,1,"[""P03""]","[""C000166""]","[""C000166_W001""]",[0.6751759052276611],[Retrieved chunk rank=1; paper_id=P03; section...,"The main purpose of RAGAS, as per the provided...",I do not have specific information about an or...,Qwen/Qwen2.5-3B-Instruct,220,greedy,success,
4,CFG_001,What issue is investigated in 'Lost in the Mid...,250,0,1,1,"[""P03""]","[""C000153""]","[""C000153_W001""]",[0.8033552765846252],[Retrieved chunk rank=1; paper_id=P03; section...,The issue investigated in 'Lost in the Middle:...,"The title ""Lost in the Middle: How Language Mo...",Qwen/Qwen2.5-3B-Instruct,220,greedy,success,

## Cell 10 — Quality checks

In [10]:
if not generation_results.empty:
    print("Rows:", len(generation_results))
    print("Successful:", int((generation_results["generation_status"] == "success").sum()))
    print("Errors:", int((generation_results["generation_status"] == "error").sum()))
    print("Missing RAG answers:", int(generation_results["rag_answer"].fillna("").str.strip().eq("").sum()))
    print("Missing No-RAG answers:", int(generation_results["no_rag_answer"].fillna("").str.strip().eq("").sum()))
    display(
        generation_results[
            ["query", "chunk_size", "overlap", "top_k", "generation_status"]
        ].head(10)
    )
else:
    print("No generated results. Check the uploaded CSV and rerun the generation cells.")

Rows: 2400
Successful: 2400
Errors: 0
Missing RAG answers: 0
Missing No-RAG answers: 0

,query,chunk_size,overlap,top_k,generation_status
0,What problem does Retrieval-Augmented Generati...,250,0,1,success
1,What are the two main components combined in t...,250,0,1,success
2,What task does Dense Passage Retrieval (DPR) t...,250,0,1,success
3,What is the main purpose of RAGAS?,250,0,1,success
4,What issue is investigated in 'Lost in the Mid...,250,0,1,success
5,What architecture is introduced in 'Attention ...,250,0,1,success
6,"What does BERT stand for, and what kind of rep...",250,0,1,success
7,What learning setting is demonstrated by GPT-3...,250,0,1,success
8,What does LoRA change when adapting a large la...,250,0,1,success
9,What is the goal of RAGChecker?,250,0,1,success

## Cell 11 — Export Module 3 results for Module 4

In [11]:
OUTPUT_CSV = "module_3_generation_results.csv"
generation_results.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")
print("Saved:", OUTPUT_CSV)

from google.colab import files
files.download(OUTPUT_CSV)

Saved: module_3_generation_results.csv